#!/bin/bash

# Root of cefode
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

PAGE_URL="file://$ROOT/test/index.html"
if [[ $1 == --url=* ]]; then
  PAGE_URL=${1:6}
  shift
fi

MODE=${1:-'Release'}

# Include utils
source "$ROOT/script/bash_utils"

# Path to cefclient
case $PLATFORM in
  darwin) CEFCLIENT="$ROOT/src/xcodebuild/$MODE/cefclient.app/Contents/MacOS/cefclient" ;;
  linux-gnu) CEFCLIENT="$ROOT/src/out/$MODE/cefclient" ;;
  *) fail 'Unsupported platform' ;;
esac

if [ ! -d "$ROOT/test/node_modules" ]; then
  has_command npm || fail 'npm is required'

  progress 'Installing dependencies of test'
  pushd "$ROOT/test" > /dev/null
  if npm install -d
  then success 'Dependencies installed'
  else fail 'Unable to install dependencies'
  fi
  popd > /dev/null
fi

$CEFCLIENT --url=$PAGE_URL \
           --remote-debugging-port=51127 \
           --no-sandbox \
           --allow-file-access-from-files

