#!/bin/bash

if [[ $1 == '--force' ]]; then
  shift
  FORCE_UPDATE='yes'
fi

MODE=${1:-'Release'}

# Root of cefode
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

# Include utils
source "$ROOT/script/bash_utils"

if [ ! -d "$ROOT/src" ]; then
  fail 'Cannot find source code'
fi

function is_git_clone_repo {
  git config remote.origin.fetch > /dev/null
}

function update_git_repo {
  if is_git_clone_repo; then
    git fetch -q origin &> /dev/null
    local REBASE_TXT STATUS
    REBASE_TXT=$(git rebase -q origin/master 2>&1)
    STATUS=$?
    if [[ $STATUS -ne 0 ]]; then
      echo "cefode scripts update failed. Conflict in $ROOT" >&2
      echo "$REBASE_TXT" >&2
      git rebase --abort 2> /dev/null
    fi
    return $STATUS
  fi
}

# Silently update myself
pushd $ROOT > /dev/null
update_git_repo
popd > /dev/null

progress 'Updating source code'

if [ -z $FORCE_UPDATE ]; then
  cd "$ROOT/src"
  CURRENT_HEAD=`git log -1 | head -n 1 | awk '{ print $2 }'`
  REMOTE_HEAD=`git ls-remote origin -h refs/heads/master | awk '{ print $1 }'`
  if [[ $? -ne 0 ]]; then
    fail 'Cannot get remote head'
  elif [[ $REMOTE_HEAD == $CURRENT_HEAD ]]; then
    success 'Already at the newest commit'
    exit
  fi
fi

[[ $PLATFORM == 'darwin' ]] || export GYP_GENERATORS=ninja 
export CEF_DIRECTORY="$ROOT/src/cef"

info 'Your local changes will be overwritten'
if python "$ROOT/depot_tools/gclient.py" sync --force
then success 'Source code updated'
else fail 'Error when updating code'
fi

progress 'Compiling'
if bash "$ROOT/script/compile" $MODE
then success 'Successfully updated'
else fail 'Cannot build cefode'
fi

